
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: ngy
    password: ngy1234
    url: jdbc:oracle:thin:@47.106.168.164:1521:orcl
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 25
      maximum-pool-size: 30
      auto-commit: false
      idle-timeout: 30000
      pool-name: TutorialsHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1 FROM DUAL

mybatis:
  type-aliases-package: cn.edu.guet.model
  mapper-locations: classpath:mapper/*.xml
server:
  servlet:
    context-path: /DormSystem
logging:
  level:
    root: info
    cn.edu.guet.mapper: debug